### ISSUE TITLE
Provide a way to reduce output

### ISSUE THREAD

**Issue by hkdobrev** [fayder/restcountries#21]
It would be great to be able to pass a parameter to limit the fields provided in the response.

For example:

```
GET https://restcountries.eu/rest/v1/all?fields=name,capital,currencies
Accept: application/json

---

200 OK
Content-Type: application/json

[  
   {  
      "name":"Afghanistan",
      "capital":"Kabul",
      "currencies":[  
         "AFN"
      ]
   },
   {  
      "name":"Åland Islands",
      "capital":"Mariehamn",
      "currencies":[  
         "EUR"
      ]
   },
   {  
      "name":"Albania",
      "capital":"Tirana",
      "currencies":[  
         "ALL"
      ]
   }
   // ....
]
```

The `?fields=name,capital,currencies` way of listing fields is very similar of the modern way the Facebook API does things. If you want to go the canonical way you could use something like this:

```
https://restcountries.eu/rest/v1/all?fields[]=name&fields[]=capital&fields[]=currencies
```

In both cases it would greatly reduce the output to only what's needed for the application and making it way faster to transfer the required content even for the full list of countries without wasting bandwidth for every field.

This would reduce the benefits of client-side and server-side caching, but it could reduce (or increase depending on the current implementation) the computational costs of the backend. :zap: 

However the greatest benefit would be the reduced time to deliver the content to the client which I think is the bottleneck in most cases. :bullettrain_side: 

Thank you for the great service!

Cheers! :beers:

**Comment by fayder** [comment]
Hello!

Thank you very much for your donation, it really helps.

This feature that you are suggesting it's in the plans but I haven't had enough time to start dealing with it, and with other planned new features.

I'm currently spending most of my time in another project, but I'll start working again on REST Countries by the end of July. When this feature, partly or complete, is implemented I will let you know. In the meantime I will leave this issue opened.

I'm glad you find the API useful

**Comment by mahmooddagga** [comment]
+1

**Comment by ruffiem** [comment]
Want someone to do it ?

**Comment by fayder** [comment]
@ruffiem Already working on it :)

**Comment by fayder** [comment]
Wow it took me more than 1 year to finally do this. It wasn't difficult, just didn't have the time :-/
Altho version 2 hasn't been formally released, it's already available by just using /v2 instead of v1. Bear in mind that the data structure has changed a bit. For example, try:

```
https://restcountries.eu/rest/v1/all?fields=name,capital,currencies
```

**Comment by hkdobrev** [comment]
I'm sorry for spamming an old thread, but just wanted to thank you @fayder for working on this and completing it! Thank you for your work! ❤️
