### ISSUE TITLE
Port to Spring Boot

### ISSUE THREAD

**Issue by geoand** [fayder/restcountries#22]
Hello,

First of all I must say this is an awesome project that is extremely useful!

I created of fork of the project (see [here](https://github.com/geoand/restcountries)) where I have replaced JBoss Rest Easy with Spring Boot.
Feel free to use any parts of the code if you like them or ask me any questions you might have.
Of course I could issue a PR to your project, perhaps in some branch other than master so you can check it out.

Regards,
George

**Comment by fayder** [comment]
Kudos! Thanks for your nice comments. I think it's great that you made a spring-boot version of it =) I'll take a look at your project.

**Comment by geoand** [comment]
Feel free to ask me anything that isn't clear about the project.

Congrats again for a great API!
