### ISSUE TITLE
Search by demonym

### ISSUE THREAD

**Issue by aliwright75** [fayder/restcountries#25]
Hi there,

Just came across this fantastic resource! I was looking for a solution where I am using another API which instead of country of origin, it only returns their nationality. I was hoping to find something where I could supply the nationality (demonym) and I could then find out the country. Are there any plans to make this available? 

Thanks!

**Comment by fayder** [comment]
Hey there. I had not thought about it. I will write this down and keep this open. When I implement it I will let you know by this same channel. Thanks for your comment.

**Comment by fayder** [comment]
@aliwright75 This feature has been added and will go live soon as part of version 2
