### ISSUE TITLE
Missing ISO countries

### ISSUE THREAD

**Issue by joostvz** [fayder/restcountries#28]
Hi, 

Great API!

I'm only missing 3 ISO countries: _Antarctica_, _Holy See_ and _Virgin Islands, U.S._. For some countries, I also see a different name than the ISO name. For example: _Vietnam_ (API) vs _Viet Nam_ (ISO). Is this done on purpose, or should these names also be updated?

Regards,
Joost

**Comment by fayder** [comment]
Hello!
I think we can add these countries and try to have ISO names for all of them. Will you do it or you'll wait for me to do it?

**Comment by fayder** [comment]
I have added these territories now.
