### ISSUE TITLE
Public API extremely slow / inaccessible

### ISSUE THREAD

**Issue by dylanpyle** [fayder/restcountries#32]
API requests seem to be somewhere between "extremely slow" and "totally inaccessible".  This one took about 54 seconds:

```
$ time curl https://restcountries.eu/rest/v1/all
... long pause ...
[{"name":"Afghanistan"... etc }]

curl https://restcountries.eu/rest/v1/all  0.02s user 0.01s system 0% cpu 54.300 total
```

**Comment by ejpersson** [comment]
Seeing the same issue now. `https://restcountries.eu/rest/v1/all` is not loading at all.

**Comment by fayder** [comment]
Hello guys. I'm aware of this issue. I contacted my server provider and apparently there's a "Electrical maintenance" going on. I'll take further steps so that this wont happen again in the future. I'm very sorry for this.

**Comment by fayder** [comment]
As you may have noticed, the service is back! I'm sorry for the downtime!
