### ISSUE TITLE
Negative timezones using diferrent dash/hyphen character

### ISSUE THREAD

**Issue by delmicio** [fayder/restcountries#34]
You can see this problem calling all countrys.
'Argentina' is using **U+2212 : MINUS SIGN**

```
"timezones": [
    "UTC−03:00"
],
```

'Honduras' is using **U+002D : HYPHEN-MINUS {hyphen or minus sign}**

```
"timezones": [
   "UTC-06:00"
],
```

**Comment by fayder** [comment]
@delmicio Timezones have been improved now. I'm keeping this open because I still need to do the work for RESTCountries v2

**Comment by delmicio** [comment]
just for the record now all times are using **U+002D** : HYPHEN-MINUS {hyphen or minus sign}

**Comment by fayder** [comment]
Fixed for v2. Thanks @delmicio
