### ISSUE TITLE
Add Portugese to translations

### ISSUE THREAD

**Issue by fayder** [fayder/restcountries#35]
```
"translations": {
    "de": "Kolumbien",
    "es": "Colombia",
    "fr": "Colombie",
    "ja": "コロンビア",
    "it": "Colombia",
    "pt": "Colômbia"
}
```

**Comment by davividal** [comment]
Portugal or Brazil? I would gladly help to translate to Brazilian Portuguese.
Also, what about translate the demonym?

**Comment by mledoze** [comment]
@davividal the demonym will be translated in here https://github.com/mledoze/countries/issues/165
you're welcome to contribute :)

**Comment by thiagokoelho** [comment]
@fayder  I'm Brazilian, I suggest use two different Portuguese languages, one for Portugal and another for Brazil, example:

`"translations": {
      "br": "Holanda",
      "de": "Niederlande",
      "es": "Países Bajos",
      "fr": "Pays-Bas",
      "ja": "オランダ",
      "it": "Paesi Bassi",
      "pt": "Países Baixos"
    }`

Could I help you?

**Comment by fayder** [comment]
Hi! Of course you can help! You can fork the master branch, make the changes in the json file (countriesV2.json) by adding the portuguese translations and make a Pull Request :) Then I take care of the rest

**Comment by fayder** [comment]
Done. Thanks @thiagokoelho
