### ISSUE TITLE
Continents / subregions are wrong in many cases

### ISSUE THREAD

**Issue by rusosnith** [fayder/restcountries#38]
I've found the region "americas" to have a lot's of foraigner countries inside (UK for example)

is there a way to report this in a per country basis?

**Comment by fayder** [comment]
Hi @rusosnith You could just write the list of countries with wrong region/subregion right here. In the case of "Americas" and "UK" when you request `/rest/v1/region/americas`, the country "United Kingdom" doesn't appear on the list.

**Comment by fayder** [comment]
Hi @rusosnith Do you still see an issue or can we close this?

**Comment by RichMatthews** [comment]
@fayder hi I would like to open this or have this addressed: https://github.com/apilayer/restcountries/issues/171

let me which issue you'd rather chat in and we can close the other
