### ISSUE TITLE
There are only 196 countries in the world

### ISSUE THREAD

**Issue by Rolos** [fayder/restcountries#39]
Hi, Why does the **all** endpoint returns 250 countries, when almost all sources state that there are between 195 and 196 countries in the world?

**Comment by fayder** [comment]
Hi! It's not only countries but also territories. I take the list from here: https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes

**Comment by Rolos** [comment]
Ah ahora entiendo, gracias hermano!
