### ISSUE TITLE
Search results shown in a better way.

### ISSUE THREAD

**Issue by Dimitrees** [fayder/restcountries#43]
Are you planning of making a panel-like feature to present each country's info? Perhaps using HTML and extracting the information from JSON.

**Comment by fayder** [comment]
Hi @Dimitrees That's not in my plans, but if you have the skills you can do it :)

**Comment by mledoze** [comment]
@Dimitrees I think this is what you are looking for: http://countries.petethompson.net/

**Comment by Dimitrees** [comment]
Yes, this is what I was thinking of. @fayder  Do you consider integrating this website to your project, or would you like to create a new one? I am asking because I am thinking of building a similar kind of work.

**Comment by fayder** [comment]
I can add a reference to it for sure
