### ISSUE TITLE
Oman - Romania

### ISSUE THREAD

**Issue by io-ma** [fayder/restcountries#44]
When calling  the https://restcountries.eu/rest/v2/name/{name} API, I get an error on Oman. The json response I get looks like this: 
`[{"name":"Oman","topLevelDomain":[".om"],"alpha2Code":"OM","alpha3Code":"OMN","callingCodes":["968"],"capital":"Muscat","altSpellings":["OM","Sultanate of Oman","Salṭanat ʻUmān"],"region":"Asia","population":4420133,"latlng":[21.0,57.0],"demonym":"Omani","area":309500.0,"gini":null,"timezones":["UTC+04:00"],"borders":["SAU","ARE","YEM"],"nativeName":"عمان","numericCode":"512","currencies":[{"code":"OMR","name":"Omani rial","symbol":"ر.ع."}],"languages":[{"iso639_1":"ar","iso639_2":"ara","name":"Arabic","nativeName":"العربية"}],"translations":{"de":"Oman","es":"Omán","fr":"Oman","ja":"オマーン","it":"oman","br":"Omã","pt":"Omã"}},{"name":"Romania","topLevelDomain":[".ro"],"alpha2Code":"RO","alpha3Code":"ROU","callingCodes":["40"],"capital":"Bucharest","altSpellings":["RO","Rumania","Roumania","România"],"region":"Europe","population":19861408,"latlng":[46.0,25.0],"demonym":"Romanian","area":238391.0,"gini":30.0,"timezones":["UTC+02:00"],"borders":["BGR","HUN","MDA","SRB","UKR"],"nativeName":"România","numericCode":"642","currencies":[{"code":"RON","name":"Romanian leu","symbol":"lei"}],"languages":[{"iso639_1":"ro","iso639_2":"ron","name":"Romanian","nativeName":"Română"}],"translations":{"de":"Rumänien","es":"Rumania","fr":"Roumanie","ja":"ルーマニア","it":"Romania","br":"Romênia","pt":"Roménia"}}]`

You can check it here: 
https://restcountries.eu/rest/v2/name/oman

Same thing happens for the equivalent V1 API.
I have an app where I click on a country and get the capital , population and demonym. 
Problem is when I click on Oman, it iterates 2 times and gets Romania's data instead. 
To reproduce it, you can go to this codepen and : click on Asia, then on Oman and you will see what I am talking about: http://codepen.io/ioiomano/pen/26e7e3a0bea5edeede771b4916888ebb
All the best and thank you for sharing your work,
Ioana Manoliu

**Comment by fayder** [comment]
Hello @io-ma 

I think you should use the "fullText" query parameter. Try this:
https://restcountries.eu/rest/v2/name/oman?fullText=true

If you don't use 'fullText' it will match any country with "oman" in its name, that's why you also get "R**oman**ia"

Hope that makes sense

**Comment by io-ma** [comment]
Ok, thank you :-)
Yes, it makes sense.
