### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by roddydairion** [fayder/restcountries#47]
When connecting to the API using Ajax I get the following error message
`XMLHttpRequest cannot load https://restcountries.eu/rest/v2/name/m. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.`

It seems that the API needs to have CORS headers enabled.

**Comment by fayder** [comment]
Hello @roddydairion I'm sorry for the delayed answer. Did you manage to solve your issue? If not, can you please specify how are you making the Ajax request?
