### ISSUE TITLE
Add status information also at success

### ISSUE THREAD

**Issue by princeofnaxos** [fayder/restcountries#52]
Momentarily, the response shows 'status: 404' when emtpy. I would like to see 'status: 200' at successful query as well.

**Comment by fayder** [comment]
The JSON response content is purely informative, you should rely on the HTTP response codes, which are 404 for Not Found and 200 for successful request

**Comment by princeofnaxos** [comment]
Ok, got that. Maybe this should be mentioned in the documentation?

**Comment by fayder** [comment]
Sure, I'll add it to the list of to-do's. Thanks
