### ISSUE TITLE
FR for some more information

### ISSUE THREAD

**Issue by princeofnaxos** [fayder/restcountries#53]
Would it be possible to get information about the following:

- country is a member of EU (https://en.wikipedia.org/wiki/Member_state_of_the_European_Union), EEA (https://en.wikipedia.org/wiki/European_Economic_Area), EFTA (https://en.wikipedia.org/wiki/European_Free_Trade_Association)

- country is SEPA member (https://en.wikipedia.org/wiki/Single_Euro_Payments_Area)

**Comment by fayder** [comment]
Hey there. There's data about EU and EFTA as "regional trade blocs" as explained here: https://restcountries.eu/#api-endpoints-regional-bloc

Of course the list of "regional blocs" can still be improved

**Comment by princeofnaxos** [comment]
Aha, I didn't interpret the regional blocs that way. Just thought it 
said that Sweden is in Europe. Think I didn't read right.
