### ISSUE TITLE
RegionalBlocs of special territories

### ISSUE THREAD

**Issue by ka-ke** [fayder/restcountries#57]
Hi,

some of the special member state territories are missing their regionalBlocs list. For example, Åland Islands of Finland is part of European Union, but it's not mentioned in the response for it. Information on special territories in EU: https://en.wikipedia.org/wiki/Special_member_state_territories_and_the_European_Union

Let me know if it's possible to develop this feature, or would it need help to get done. Thanks.

**Comment by fayder** [comment]
Hi @ka-ke It is most definitely possible to improve the data. All the help is very welcome :)

**Comment by fayder** [comment]
Improvements have been deployed!
