### ISSUE TITLE
https://restcountries.eu/rest/v2/all in this API some countries calling codes are missing

### ISSUE THREAD

**Issue by parasmesanjay** [fayder/restcountries#58]
API :- https://restcountries.eu/rest/v2/all 
when i hit his api it give me data but in this data i see some countries calling codes are missing which i want in response.
example :- Antarctica (for this country calling code missing)

**Comment by fayder** [comment]
Hi @parasmesanjay I will look into it. Thanks

**Comment by fayder** [comment]
This is fixed now
