### ISSUE TITLE
Where is England, Scotland, Wales and Ireland ?

### ISSUE THREAD

**Issue by workallday** [fayder/restcountries#62]
Where are these countries ? Fairly standard tbh

**Comment by fayder** [comment]
Hey @workallday 

England, Scotland, Wales and Northern Ireland are represented by "United Kingdom of Great Britain and Northern Ireland"

Ireland does appear by itself `http://restcountries.eu/rest/v2/name/ireland`

The list of countries is taken from this wiki page https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes

**Comment by TomDeSmet** [comment]
It's kind of a bummer that those aren't in the list by themselves...
