### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by namnamir** [fayder/restcountries#63]
Hi there,

I am willing to add the Farsi translation to the db. Then Iranian and Afghan developers can use it :)

I don't know how it does work. Should I add it and ask for pull?

**Comment by fayder** [comment]
Hey @namnamir Yes, you'd need to add the translations on this file `restcountries/src/main/resources/countriesV2.json` and make a Pull Request

**Comment by namnamir** [comment]
thank you. I'll do it and will send a pull request :+1:
