### ISSUE TITLE
Search by Capital city end-point is Not working Correctly

### ISSUE THREAD

**Issue by dejanljevar** [fayder/restcountries#67]
Hi, 

`https://restcountries.eu/rest/v2/capital/gr`

I have noticed that if you type in search field "gr" result will be "Croatia", 
but capital of this country is Zagreb. Is this known issue ? 

p.s. Thanks for such a great API !

Regards, 
Dejan

**Comment by fayder** [comment]
Hey! This is because the word "Za**gr**eb" contains **gr**
