### ISSUE TITLE
CORS issue in ajax request

### ISSUE THREAD

**Issue by berserkmustdie** [fayder/restcountries#73]
Hi when I make ajax request I got  such error `Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response`

1 variant:
           $.get("https://restcountries.eu/rest/v2/all?fields=name").done(function (country) {
                console.dir(country);
                var options = "";
                for(var i=0; i<country.length; i++) {
                    options += "<option value='"+country[i].name+"'>"+country[i].name+"</option>";
                }
                $('#'+HTMLelement).append(options);
            });

2 variant
            $.ajax({
                type : "GET",
                url : "https://restcountries.eu/rest/v2/all?fields=name",
                dataType: 'json',
                success: function(country) {
                    console.dir(country);
                    var options = "";
                    for(var i=0; i<country.length; i++) {
                        options += "<option value='"+country[i].name+"'>"+country[i].name+"</option>";
                    }
                    $('#'+HTMLelement).append(options);
                },
                error: function(xhr) {
                    console.log(xhr.responseText);
                    console.log("countryList ajax request failed");
                }
            });

**Comment by mledoze** [comment]
Well, the error message says it all: `Request header field Authorization is not allowed by Access-Control-Allow-Headers`

When you perform a GET on `https://restcountries.eu/rest/v2/all?fields=name`, the server returns the following header `Access-Control-Allow-Headers` which contains `Accept, X-Requested-With`; as you can see the `Authorization` header is not in this list.

So you need to perform this request without the `Authorization` header.
